# Generated by Django 4.2.1 on 2023-05-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_time_ending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='photo',
            new_name='image',
        ),
    ]
