# Generated by Django 4.2.1 on 2023-05-26 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_photo_auctionlisting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='time_ending',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 16, 40, 12, 447400, tzinfo=datetime.timezone.utc)),
        ),
    ]
