# Generated by Django 4.2.1 on 2023-05-26 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctionlisting_user_alter_auctionlisting_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='time_ending',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 23, 36, 32, 773889, tzinfo=datetime.timezone.utc)),
        ),
    ]
