# Generated by Django 4.2.1 on 2023-05-28 01:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionlisting_time_ending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='item_ratings',
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='time_ending',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 1, 51, 49, 701552, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
