# Generated by Django 4.2.1 on 2023-05-28 01:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_auctionlisting_item_ratings_comment_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='time_ending',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 1, 55, 17, 147045, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
