# Generated by Django 4.2.1 on 2023-05-29 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auctionlisting_time_ending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='item_comments',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='time_ending',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 2, 56, 42, 876833, tzinfo=datetime.timezone.utc)),
        ),
    ]
