# Generated by Django 4.2.1 on 2023-05-29 03:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_auctionlisting_item_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorited_items',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auctions.auctionlisting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='time_ending',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 3, 4, 15, 895471, tzinfo=datetime.timezone.utc)),
        ),
    ]
