# Generated by Django 4.2.1 on 2023-05-29 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_auctionlisting_time_ending'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist_item',
            field=models.ManyToManyField(related_name='+', to='auctions.auctionlisting'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='time_ending',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 17, 22, 50, 382433, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
