# Generated by Django 4.2.1 on 2023-05-29 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_user_watchlist_item_alter_auctionlisting_time_ending_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='watchlist_item',
            new_name='watchlist_items',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='time_ending',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 17, 25, 53, 730739, tzinfo=datetime.timezone.utc)),
        ),
    ]
