# Generated by Django 4.2.1 on 2023-05-29 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_auctionlisting_time_ending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='time_ending',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 19, 33, 26, 591456, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist_items',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='auctions.auctionlisting'),
        ),
    ]
