# Generated by Django 4.2.1 on 2023-05-29 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_auctionlisting_time_ending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='time_ending',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 19, 54, 47, 664354, tzinfo=datetime.timezone.utc)),
        ),
    ]
