# Generated by Django 4.2.1 on 2023-05-30 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_auctionlisting_time_ending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='time_ending',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 3, 36, 13, 367420, tzinfo=datetime.timezone.utc)),
        ),
    ]
