# Generated by Django 4.2.1 on 2023-05-30 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auctionlisting_auction_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='time_ending',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 20, 14, 27, 303705, tzinfo=datetime.timezone.utc)),
        ),
    ]
